package personal.wl.jspos.pos;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BRANCH".
 */
@Entity
public class Branch {

    @Id(autoincrement = true)
    private Long id;
    private String braid;
    private String braname;
    private String brasname;
    private String bratype;
    private String Status;

    @Generated
    public Branch() {
    }

    public Branch(Long id) {
        this.id = id;
    }

    @Generated
    public Branch(Long id, String braid, String braname, String brasname, String bratype, String Status) {
        this.id = id;
        this.braid = braid;
        this.braname = braname;
        this.brasname = brasname;
        this.bratype = bratype;
        this.Status = Status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBraid() {
        return braid;
    }

    public void setBraid(String braid) {
        this.braid = braid;
    }

    public String getBraname() {
        return braname;
    }

    public void setBraname(String braname) {
        this.braname = braname;
    }

    public String getBrasname() {
        return brasname;
    }

    public void setBrasname(String brasname) {
        this.brasname = brasname;
    }

    public String getBratype() {
        return bratype;
    }

    public void setBratype(String bratype) {
        this.bratype = bratype;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

}
